//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public int ID_CARRITO { get; set; }
        public string Nombre { get; set; }
        public int ID_MARCA { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public string ID_USUARIO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual MARCA MARCA { get; set; }
    }
}
