//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMICILIO
    {
        public int ID_DOMICILIO { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string canton { get; set; }
        public string direccion { get; set; }
        public string ID_USUARIO { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
