//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID_FACTURA { get; set; }
        public string nombre_dispositivo { get; set; }
        public string detalle { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string TELEFONO { get; set; }
    }
}
