//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIFERICO
    {
        [Key]
        [IDExiste]
        [Display(Name = "ID Periferico")]
        public int ID_PERIFERICO { get; set; }
        [StringLength(60, ErrorMessage = "El nombre debe ser de 60 maximo.")]
        public string nombre_periferico { get; set; }
        public int cant_disp { get; set; }
        [Range(1, 999999999, ErrorMessage = "El ID debe ser de 10 dígitos maximo.")]
        public decimal precio { get; set; }
        public int ID_MARCA { get; set; }
    
        public virtual MARCA MARCA { get; set; }

        public class IDExiste : ValidationAttribute
        {
            protected override ValidationResult IsValid(Object value, ValidationContext validationContext)
            {
                using (TiendaVGEntities db = new TiendaVGEntities())
                {
                    int id = (int)value;
                    if (db.PERIFERICO.Where(x => x.ID_PERIFERICO == id).Count() > 0)
                    {
                        return new ValidationResult("El ID ya existe.");
                    }
                    return ValidationResult.Success;
                }
            }
        }
    }
}
